"use client";

import { education } from "@/data/content";
import { useLocale } from "@/components/locale-context";
import { t } from "@/lib/i18n";
import { Eyebrow, SourceTag } from "@/components/ui";

export default function AboutPage() {
  const { locale } = useLocale();
  const zh = locale === "zh";
  return <div className="page-frame"><section className="page-intro"><Eyebrow>About / 03</Eyebrow><h1>ABOUT<br /><span style={{ color: "var(--red)" }}>THE ARCHIVE.</span></h1><p>{zh ? "這一頁補上檔案之外的脈絡：我關注哪些問題、如何整理資料，以及哪些內容還沒有公開。" : "This page adds the context around the archive: the questions I follow, how I organize material, and what has not been made public yet."}</p></section><div className="about-grid"><div><section className="about-block"><h2>{zh ? "背景 / Background" : "Background / 背景"}</h2><p>{zh ? "我關注大型語言模型如何進入真實系統：從任務拆解與評測，到上傳流程、內容權限，以及之後仍能回看的資料組織。這個網站把目前的專案紀錄整理成一套可以持續擴充的個人知識系統。" : "I study how language models enter real systems: from task decomposition and evaluation to upload flows, content permissions, and records that remain useful later. This site organizes current project material into a personal knowledge system that can keep growing."}</p></section><section className="about-block"><h2>{zh ? "教育 / Education" : "Education / 教育"}</h2><div className="education-grid">{education.map((item) => <div className="education-item" key={item.period}><span className="education-year">{item.period}</span><div><strong>{t(item.school, locale)}</strong><span>{t(item.detail, locale)}</span></div></div>)}</div></section></div><div><section className="about-block"><h2>{zh ? "實習 / Internships" : "Internships / 實習"}</h2><div className="placeholder-note">{zh ? "實習單位、時間與工作內容仍待核驗，確認後再補入。" : "Internship organizations, dates, and responsibilities will be added after verification."}</div></section><section className="about-block"><h2>{zh ? "關注領域 / Areas of attention" : "Areas of attention / 關注領域"}</h2><div className="topic-index about-topics"><span className="topic-item"><b>01</b>{zh ? "大型語言模型進入真實系統" : "Language models in real systems"}</span><span className="topic-item"><b>02</b>{zh ? "可追溯的系統評測" : "Traceable system evaluation"}</span><span className="topic-item"><b>03</b>{zh ? "內容、權限與上傳流程" : "Content, permissions, and upload flows"}</span></div></section><section className="about-block contact-block"><h2>{zh ? "聯絡方式 / Contact" : "Contact / 聯絡方式"}</h2><p className="placeholder-note">{zh ? "公開信箱與其他聯絡方式稍後補上。" : "A public email and other contact channels will be added later."}</p><SourceTag>{zh ? "資料核驗中" : "Verification in progress"}</SourceTag></section></div></div></div>;
}
