"use client";

import { education, internships } from "@/data/content";
import { useLocale } from "@/components/locale-context";
import { t } from "@/lib/i18n";
import { Eyebrow, SourceTag } from "@/components/ui";

export default function AboutPage() {
  const { locale } = useLocale();
  const zh = locale === "zh";
  return <div className="page-frame"><section className="page-intro"><Eyebrow>About / 03</Eyebrow><h1>ABOUT<br /><span style={{ color: "var(--red)" }}>THE ARCHIVE.</span></h1><p>{zh ? "這一頁補上檔案之外的脈絡：我的學習背景、實習記錄，以及目前持續整理的問題。" : "This page adds the context around the archive: my education, internship record, and the questions I continue to organize."}</p></section><div className="about-grid"><div><section className="about-block"><h2>{zh ? "背景 / Background" : "Background / 背景"}</h2><p>{zh ? "我已完成中南大學計算機科學與技術本科學習並取得學位。這幾年的學習與項目主要分成兩條線：一條是大型語言模型、視覺感知與無人機控制研究；另一條是 Web、移動端與服務端系統實作。這個網站按照來源整理每個項目的設計、實驗、分工與限制。" : "I completed a BSc in Computer Science and Technology at Central South University. My recent work follows two lines: language models, visual perception, and UAV control; and practical web, mobile, and server systems. This site organizes each project's design, experiments, responsibilities, and limits around its sources."}</p></section><section className="about-block"><h2>{zh ? "教育 / Education" : "Education / 教育"}</h2><div className="education-grid">{education.map((item) => <div className="education-item" key={item.period}><span className="education-year">{item.period}</span><div><strong>{t(item.school, locale)}</strong><span>{t(item.detail, locale)}</span></div></div>)}</div></section></div><div><section className="about-block"><h2>{zh ? "實習 / Internships" : "Internships / 實習"}</h2><div className="education-grid">{internships.map((item) => <div className="education-item internship-item" key={item.period}><span className="education-year">{item.period}</span><div><strong>{t(item.company, locale)}</strong><span>{t(item.detail, locale)}</span><p>{t(item.note, locale)}</p></div></div>)}</div></section><section className="about-block"><h2>{zh ? "關注領域 / Areas of attention" : "Areas of attention / 關注領域"}</h2><div className="topic-index about-topics"><span className="topic-item"><b>01</b>{zh ? "大型語言模型進入真實系統" : "Language models in real systems"}</span><span className="topic-item"><b>02</b>{zh ? "可追溯的系統評測" : "Traceable system evaluation"}</span><span className="topic-item"><b>03</b>{zh ? "跨端系統、內容與權限" : "Cross-platform systems, content, and permissions"}</span></div></section><section className="about-block contact-block"><h2>{zh ? "聯絡方式 / Contact" : "Contact / 聯絡方式"}</h2><p className="placeholder-note">{zh ? "公開信箱與其他聯絡方式稍後補上。" : "A public email and other contact channels will be added later."}</p><SourceTag>{zh ? "資料持續整理" : "Archive in progress"}</SourceTag></section></div></div></div>;
}
