"use client";

import { education } from "@/data/content";
import { useLocale } from "@/components/locale-context";
import { t } from "@/lib/i18n";
import { Eyebrow, SourceTag } from "@/components/ui";

export default function AboutPage() {
  const { locale } = useLocale();
  const zh = locale === "zh";
  return <div className="page-frame"><section className="page-intro"><Eyebrow>About / 03</Eyebrow><h1>ABOUT<br /><span style={{ color: "var(--red)" }}>THE ARCHIVE.</span></h1><p>{zh ? "这里是系统的简短背景，而不是求职履历。需要更具体的内容时，从项目档案或问答入口进入。" : "A short context for the system, not a job-seeking résumé. For specifics, enter through the project archive or Ask interface."}</p></section><div className="about-grid"><div><section className="about-block"><h2>{zh ? "背景 / Background" : "Background / 背景"}</h2><p>{zh ? "我关注大模型如何进入真实系统：从任务拆解和评测，到上传链路、内容权限与可复盘的资料组织。这个站点把现有项目记录整理成一个可以继续扩展的个人 AI 知识系统。" : "I study how language models enter real systems: from task decomposition and evaluation to upload flows, content permissions, and records that can be revisited. This site organizes existing project records into a personal AI knowledge system that can keep evolving."}</p></section><section className="about-block"><h2>{zh ? "教育 / Education" : "Education / 教育"}</h2><div className="education-grid">{education.map((item) => <div className="education-item" key={item.period}><span className="education-year">{item.period}</span><div><strong>{t(item.school, locale)}</strong><span>{t(item.detail, locale)}</span></div></div>)}</div></section></div><div><section className="about-block"><h2>{zh ? "实习 / Internships" : "Internships / 实习"}</h2><div className="placeholder-note">{zh ? "待核验：实习单位、时间与职责。当前不将未核验信息写成经历。" : "Pending verification: internship organizations, dates, and responsibilities. Unverified information is not presented as experience."}</div></section><section className="about-block"><h2>{zh ? "关注领域 / Areas of attention" : "Areas of attention / 关注领域"}</h2><div className="topic-index about-topics"><span className="topic-item"><b>01</b>{zh ? "大模型进入真实系统" : "Language models in real systems"}</span><span className="topic-item"><b>02</b>{zh ? "可追溯的系统评测" : "Traceable system evaluation"}</span><span className="topic-item"><b>03</b>{zh ? "内容、权限与上传链路" : "Content, permissions, and upload flows"}</span></div></section><section className="about-block contact-block"><h2>{zh ? "联系方式 / Contact" : "Contact / 联系方式"}</h2><p className="placeholder-note">{zh ? "待补充：公开邮箱或其他联系方式。" : "Pending: public email or another contact channel."}</p><SourceTag>{zh ? "档案说明 / 资料待核验" : "Archive note / verification pending"}</SourceTag></section></div></div></div>;
}
